CREATE TABLE `defects` (
	`id` text PRIMARY KEY NOT NULL,
	`project_id` text NOT NULL,
	`scan_id` text NOT NULL,
	`detected_at` integer NOT NULL,
	`class` text NOT NULL,
	`severity` integer NOT NULL,
	`blast_radius` real NOT NULL,
	`confidence` real NOT NULL,
	`difficulty` real NOT NULL,
	`priority` real NOT NULL,
	`band` text NOT NULL,
	`file` text NOT NULL,
	`line_start` integer NOT NULL,
	`line_end` integer NOT NULL,
	`rule_id` text NOT NULL,
	`human_explanation` text NOT NULL,
	`code_evidence` text NOT NULL,
	`status` text DEFAULT 'open' NOT NULL,
	`fix_tier` integer,
	`fix_branch` text,
	`fix_test_path` text,
	`resolved_at` integer,
	`resolved_commit` text,
	FOREIGN KEY (`project_id`) REFERENCES `projects`(`id`) ON UPDATE no action ON DELETE no action
);
